
services:
  api:
    # container_name: api_container
    build: .
    networks:
      - usersapp
    ports:
      - "4040:4040"
    volumes:
      - .:/app
    depends_on:
      - mysqldb

  mysqldb:
    # container_name: mysqldb_container
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 'Hj24KhuP'
      MYSQL_DATABASE: usersapp
      MYSQL_USER: user_manager
      MYSQL_PASSWORD: 'usersapp@321'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - usersapp

volumes:
  mysql-data:

networks:
  usersapp:
