version: '3.8'

services:
  api:
    build: .
    networks:
      - usersapp
    ports:
      - "5050:5050"
    volumes:
      - .:/app
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-Hj24KhuP}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-usersapp}
      MYSQL_USER: ${MYSQL_USER:-user_manager}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-usersapp@321}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - usersapp

volumes:
  mysql-data:

networks:
  usersapp:
